AZURE_WORKSPACE_CREDENTIALS:
  subscription_id:
  resource_group: 
  workspace_name: 

AZ_OPEN_CLOSED_ATTAPOL:
  datastore: container_open_closed_attapol
  dataset: container_open_closed_attapol/

AZ_OPEN_CLOSED_TEST:
  datastore: opened_closed_test_dataset
  dataset: opened_closed_test_dataset

OPEN_CLOSED_LABELS:
  - containers_open_closed_20221115_074852

YOLO_V5_PARAMETERS:
  batch_size: 32
  epochs: 2
  imgsz: 50
  device: 'cpu'
  pretrained_model : 'yolov5s.pt'

MLFLOW:
  exp_name : 'small_models'
  exp_containers_name : 'yolo_open_closed'

PREDICTION_MODEL:
  model: 'machine_learning\best.pt'
  threshold: 0.3

YOLO_V8_PARAMETERS:
  batch_size: 16
  epochs: 60
  imgsz: 500
  device: 0
  pretrained_model : 'yolov8l.pt'