path: C:\GIS\Projektai\VASA_siuksles\ML\vasa\machine_learning_open_closed # dataset root dir
train: train/images/  # train images (relative to 'path') 
val: val/images/ # val images (relative to 'path')

# number of classes
nc: 2

# class names
names: ["closed", "opened"]